[prefacio]
== Prefacio

=== Escribiendo el Libro de Bitcoin

Yo (Andreas) me topé por primera vez con Bitcoin a mediados de 2011. Mi reacción inmediata fue más o menos "¡Pfft! ¡Dinero nerd!" y lo ignoré durante otros seis meses, sin comprender su importancia. Ésta es una reacción que he visto repetida entre muchas de las personas más inteligentes que conozco, lo que me da cierto consuelo. La segunda vez que me encontré con Bitcoin, en una discusión en una lista de correo, decidí leer el documento técnico escrito por Satoshi Nakamoto y ver de qué se trataba. Todavía recuerdo el momento en que terminé de leer esas nueve páginas, cuando me di cuenta de que Bitcoin no era simplemente una moneda digital, sino una red de confianza que también podía proporcionar la base para mucho más que solo monedas. Darme cuenta de que "esto no es dinero, es una red de confianza descentralizada" me inició en un viaje de cuatro meses para devorar cada fragmento de información sobre Bitcoin que pude encontrar. Me obsesioné y cautivé, pasando 12 horas o más cada día pegado a una pantalla, leyendo, escribiendo, codificando y aprendiendo todo lo que podía. Salí de este estado de fuga, con más de 20 libras menos por la falta de comidas consistentes, decidido a dedicarme a trabajar en Bitcoin.

Dos años más tarde, después de crear una serie de pequeñas empresas emergentes para explorar diversos servicios y productos relacionados con Bitcoin, decidí que era hora de escribir mi primer libro. Bitcoin fue el tema que me llevó a un frenesí de creatividad y consumió mis pensamientos; Era la tecnología más emocionante que había encontrado desde Internet. Había llegado el momento de compartir mi pasión por esta asombrosa tecnología con una audiencia más amplia.

=== Público Objetivo

Este libro está destinado principalmente a programadores. Si puede utilizar un lenguaje de programación, este libro le enseñará cómo funcionan las monedas criptográficas, cómo utilizarlas y cómo desarrollar software que funcione con ellas. Los primeros capítulos también son adecuados como una introducción en profundidad a Bitcoin para los no codificadores, aquellos que intentan comprender el funcionamiento interno de Bitcoin y las criptomonedas.

=== ¿Por Qué Hay Insectos en la Portada?

La hormiga cortadora de hojas es una especie que exhibe un comportamiento muy complejo en un superorganismo de colonia, pero cada hormiga individual opera según un conjunto de reglas simples impulsadas por la interacción social y el intercambio de olores químicos (feromonas). Según Wikipedia: "Junto a los humanos, las hormigas cortadoras de hojas forman las sociedades animales más grandes y complejas de la Tierra". Las hormigas cortadoras de hojas en realidad no comen hojas, sino que las usan para cultivar un hongo, que es la fuente central de alimento de la colonia. ¿Obtén éso? ¡Estas hormigas están cultivando!

Aunque las hormigas forman una sociedad basada en castas y tienen una reina para producir descendencia, no existe una autoridad central o un líder en una colonia de hormigas. El comportamiento altamente inteligente y sofisticado exhibido por una colonia multimillonaria es una propiedad emergente de la interacción de los individuos en una red social.

La naturaleza demuestra que los sistemas descentralizados pueden ser resilientes y producir una complejidad emergente y una sofisticación increíble sin la necesidad de una autoridad central, jerarquía o partes complejas.

Bitcoin es una red descentralizada altamente sofisticada que puede respaldar innumerables procesos financieros. Sin embargo, cada nodo de la red Bitcoin sigue unas cuantas reglas sencillas. La interacción entre muchos nodos es lo que conduce al surgimiento de un comportamiento sofisticado, no una complejidad inherente o confianza en un solo nodo. Como una colonia de hormigas, la red Bitcoin es una red resistente de nodos simples que siguen reglas simples y que juntos pueden hacer cosas asombrosas sin ninguna coordinación central.

=== Las Convenciones Usadas en Este Libro

En este libro se utilizan las siguientes convenciones tipográficas:

_Itálica_:: Indica nuevos términos, URL, direcciones de correo electrónico, nombres de archivos y extensiones de archivos.

+Ancho Constante+:: Se utiliza para listados de programas, así como dentro de párrafos para hacer referencia a elementos del programa, como nombres de funciones o variables, bases de datos, tipos de datos, variables de entorno, declaraciones y palabras clave.

**`Negrita de Ancho Constante`**:: Muestra comandos u otro texto que el usuario debe escribir literalmente.

_++Cursiva de Ancho Constante++_:: Muestra texto que debe reemplazarse con valores proporcionados por el usuario o por valores determinados por el contexto.


[TIP]
====
Este elemento significa un consejo o sugerencia.
====

[NOTE]
====
Este elemento significa una nota general.
====

[WARNING]
====
Este elemento indica una advertencia o precaución.
====

=== Ejemplos de Código

Todos los fragmentos de código se pueden replicar en la mayoría de los sistemas operativos con una instalación mínima de compiladores e intérpretes para los lenguajes correspondientes. Cuando sea necesario, proporcionamos instrucciones de instalación básicas y ejemplos paso a paso del resultado de esas instrucciones.

Algunos de los fragmentos de código y la salida del código se han reformateado para imprimir. En todos estos casos, las líneas se han dividido mediante un carácter de barra invertida (\), seguido de un carácter de nueva línea. Al transcribir los ejemplos, elimine esos dos caracteres y vuelva a unir las líneas y debería ver resultados idénticos a los que se muestran en el ejemplo.

Todos los fragmentos de código utilizan valores y cálculos reales siempre que sea posible, de modo que pueda construir de un ejemplo a otro y ver los mismos resultados en cualquier código que escriba para calcular los mismos valores.

=== Usando Ejemplos de Código

Este libro está aquí para ayudarle a realizar su trabajo. En general, si se ofrece código de ejemplo con este libro, puede utilizarlo en sus programas y documentación. No es necesario que se comunique con nosotros para solicitar permiso a menos que esté reproduciendo una parte importante del código. Por ejemplo, escribir un programa que utilice varios fragmentos de código de este libro no requiere permiso. Vender o distribuir ejemplos de libros de O'Reilly requiere permiso. Responder una pregunta citando este libro y citando código de ejemplo no requiere permiso. Incorporar una cantidad significativa de código de ejemplo de este libro en la documentación de su producto requiere permiso.

Apreciamos la atribución, pero no la exigimos. Una atribución suele incluir [.keep-together]#el título,# el autor, el editor y el ISBN. Por ejemplo: “_Mastering Bitcoin_, 3.ª ed., por [.keep-together]#Andreas M.# Antonopoulos y David A. Harding (O'Reilly). Copyright 2024 David Harding, ISBN 978-1-098-15009-9.”

Algunas ediciones de este libro se ofrecen bajo una licencia de código abierto, como https://oreil.ly/RzUHE[CC-BY-NC], en cuyo caso se aplican los términos de esa licencia.

Si cree que su uso de ejemplos de código queda fuera del uso legítimo o del permiso otorgado anteriormente, no dude en contactarnos en pass:[<a href="mailto:permissions@oreilly.com">permissions@oreilly.com</a> ].

=== Direcciones y Transacciones de Bitcoin en Este Libro

Las direcciones, transacciones, claves, códigos QR y datos de blockchain de Bitcoin utilizados en este libro son, en su mayor parte, reales. Eso significa que puede navegar por la cadena de bloques, ver las transacciones ofrecidas como ejemplos, recuperarlas con sus propios scripts o programas, etc.

Sin embargo, tenga en cuenta que las claves privadas utilizadas para construir direcciones están impresas en este libro o han sido "quemadas". Eso significa que si envía dinero a cualquiera de estas direcciones, el dinero se perderá para siempre o, en algunos casos, todos los que puedan leer el libro podrán recibirlo utilizando las claves privadas impresas aquí.

[WARNING]
====
NO ENVÍE DINERO A NINGUNA DE LAS DIRECCIONES EN ESTE LIBRO. Otro lector se llevará su dinero o lo perderá para siempre.
====

=== O'Reilly Online Learning
[role = "ormenabled"]
[NOTE]
====
Desde hace más de 40 años, pass:[<a href="https://oreilly.com" class="orm:hideurl"><em class="hyperlink">O’Reilly Media</em></a>] ha proporcionado tecnología y capacitación empresarial, conocimientos y perspectivas para ayudar a las empresas a tener éxito.
====

Nuestra red única de expertos e innovadores comparte su conocimiento y experiencia a través de libros, artículos y nuestra plataforma de aprendizaje en línea. La plataforma de aprendizaje en línea de O'Reilly le brinda acceso bajo demanda a cursos de capacitación en vivo, rutas de aprendizaje en profundidad, entornos de codificación interactivos y una amplia colección de texto y video de O'Reilly y más de 200 editoriales más. Para más información visitepass:[<a href="https://oreilly.com" class="orm:hideurl"><em>https://oreilly.com</em></a>].

=== Como Contactarnos

Por favor dirija sus comentarios y preguntas sobre este libro al editor:

++++
<ul class="simplelist">
  <li>O’Reilly Media, Inc.</li>
  <li>1005 Gravenstein Highway North</li>
  <li>Sebastopol, CA 95472</li>
  <li>800-889-8969 (in the United States or Canada)</li>
  <li>707-829-7019 (international or local)</li>
  <li>707-829-0104 (fax)</li>
  <li><a class="email" href="mailto:support@oreilly.com"><em>support@oreilly.com</em></a></li>
  <li><a href="https://www.oreilly.com/about/contact.html"><em>https://www.oreilly.com/about/contact.html</em></a></li>
</ul>
++++

Tenemos una página web para este libro, donde enumeramos erratas, ejemplos y cualquier información adicional. Puede acceder a esta página en el enlace :$$https://oreil.ly/MasteringBitcoin3e$$[].

++++
<!--Don't forget to update the link above.-->
++++

Para noticias e información sobre nuestros libros y cursos, visite link:$$https://oreilly.com$$[].

Encuéntranos en LinkedIn: link:$$https://linkedin.com/company/oreilly-media$$[].

Síganos en Twitter: link:$$https://twitter.com/oreillymedia$$[].

Míranos en YouTube: link:$$https://youtube.com/oreillymedia$$[].


=== Contacte a los Autores

++++
<p class="left-align">
Puede contactar con Andreas M. Antonopoulos en su sitio personal:
<span class="keep-together"><a href="https://antonopoulos.com"><em class="hyperlink">https://antonopoulos.com</em></a>.</span></p>
++++

Sigue a Andreas en Facebook:
link:$$https://facebook.com/AndreasMAntonopoulos$$[].

Sigue a Andreas en Twitter:
link:$$https://twitter.com/aantonop$$[].

Sigue a Andreas en LinkedIn:
link:$$https://linkedin.com/company/aantonop$$[].

Muchas gracias a todos los patrocinadores de Andreas que apoyan su trabajo mediante donaciones mensuales. Puedes seguir su página de Patreon aquí:
link:$$https://patreon.com/aantonop$$[].

Información sobre _Mastering Bitcoin_, así como la edición abierta de Andreas y sus traducciones, está disponible en
link:$$https://bitcoinbook.info$$[].

Puede contactar a David A. Harding en su sitio personal:
link:$$https://dtrt.org$$[].

=== Agradecimientos a la Primera y Segunda Edición

_Por Andreas M. Antonopoulos_

Este libro representa los esfuerzos y contribuciones de muchas personas. Agradezco toda la ayuda que recibí de amigos, colegas e incluso completos desconocidos, que se unieron a mí en este esfuerzo por escribir el libro técnico definitivo sobre criptomonedas y Bitcoin.

Es imposible hacer una distinción entre la tecnología Bitcoin y la comunidad Bitcoin, y este libro es tanto un producto de esa comunidad como un libro sobre la tecnología. Mi trabajo en este libro fue alentado, alentado, apoyado y recompensado por toda la comunidad Bitcoin desde el principio hasta el final. Más que nada, este libro me ha permitido ser parte de una comunidad maravillosa durante dos años y no puedo agradecerles lo suficiente por aceptarme en esta comunidad. Hay demasiadas personas para mencionarlas por su nombre: personas que he conocido en conferencias, eventos, seminarios, encuentros, reuniones de pizza y pequeñas reuniones privadas, así como muchos que se comunicaron conmigo a través de Twitter, reddit, bitcointalk. org y en GitHub que han tenido un impacto en este libro. Cada idea, analogía, pregunta, respuesta y explicación que encuentras en este libro fue en algún momento inspirada, probada o mejorada a través de mis interacciones con la comunidad. Gracias por todo tu apoyo; sin ti este libro no habría existido. Estaré eternamente agradecido.

El viaje para convertirse en autor comienza mucho antes del primer libro, por supuesto. Mi primer idioma (y mis estudios) fue el griego, por lo que tuve que tomar un curso de recuperación de escritura en inglés en mi primer año de universidad. Debo agradecer a Diana Kordas, mi profesora de escritura en inglés, quien me ayudó a desarrollar confianza y habilidades ese año. Posteriormente, como profesional, desarrollé mis habilidades de redacción técnica sobre el tema de centros de datos, escribiendo para la revista _Network World_. Debo agradecer a John Dix y John Gallant, quienes me dieron mi primer trabajo como columnista en Network World, y a mi editor Michael Cooney y mi colega Johna Till Johnson, quienes editaron mis columnas y las prepararon para su publicación. Escribir 500 palabras por semana durante cuatro años me dio suficiente experiencia como para considerar eventualmente convertirme en autor.

Gracias también a quienes me apoyaron cuando envié mi propuesta de libro a O'Reilly proporcionándome referencias y revisando la propuesta. Específicamente, gracias a John Gallant, Gregory Ness, Richard Stiennon, Joel Snyder, Adam B. Levine, Sandra Gittlen, John Dix, Johna Till Johnson, Roger Ver y Jon Matonis. Un agradecimiento especial a Richard Kagan y Tymon Mattoszko, quienes revisaron las primeras versiones de la propuesta, y a Matthew Taylor, quien editó la propuesta.

Gracias a Cricket Liu, autor del título de O'Reilly _DNS and BIND_, quien me presentó a O'Reilly. Gracias también a Michael Loukides y Allyson MacDonald de O'Reilly, quienes trabajaron durante meses para ayudar a que este libro se hiciera realidad. Allyson fue especialmente paciente cuando se incumplieron los plazos y se retrasaron las entregas cuando la vida intervino en nuestro cronograma planificado. Para la segunda edición, agradezco a Timothy McGovern por guiar el proceso, a Kim Cofer por editar pacientemente y a Rebecca Panzer por ilustrar muchos diagramas nuevos.

Los primeros borradores de los primeros capítulos fueron los más difíciles, porque Bitcoin es un tema difícil de desentrañar. Cada vez que tiraba de un hilo de la tecnología Bitcoin, tenía que tirar de todo. En repetidas ocasiones me quedé estancado y un poco abatido mientras luchaba por hacer que el tema fuera fácil de entender y crear una narrativa en torno a un tema técnico tan denso. Finalmente, decidí contar la historia de Bitcoin a través de las historias de las personas que usan Bitcoin y todo el libro se volvió mucho más fácil de escribir. Debo agradecer a mi amigo y mentor, Richard Kagan, quien me ayudó a desentrañar la historia y superar los momentos de bloqueo del escritor. Agradezco a Pamela Morgan, quien revisó los primeros borradores de cada capítulo en la primera y segunda edición del libro y formuló las preguntas difíciles para mejorarlos. Además, gracias a los desarrolladores del grupo San Francisco Bitcoin Developers Meetup, así como a Taariq Lewis y Denise Terry por ayudar a probar el material inicial. Gracias también a Andrew Naugler por el diseño infográfico.

Durante el desarrollo del libro, publiqué los primeros borradores en GitHub e invité a comentarios del público. En respuesta se presentaron más de cien comentarios, sugerencias, correcciones y contribuciones. Esas contribuciones se reconocen explícitamente, con mi agradecimiento, en <<github_contrib>>. Sobre todo, mi más sincero agradecimiento a mis editores voluntarios de GitHub, Ming T. Nguyen (primera edición) y Will Binns (segunda edición), quienes trabajaron incansablemente para seleccionar, administrar y resolver solicitudes de extracción, emitir informes y realizar correcciones de errores en GitHub. .

Una vez redactado el libro, pasó por varias rondas de revisión técnica. Gracias a Cricket Liu y Lorne Lantz por su exhaustiva revisión, comentarios y apoyo.

Varios desarrolladores de Bitcoin contribuyeron con ejemplos de código, reseñas, comentarios y aliento. Gracias a Amir Taaki y Eric Voskuil, por ejemplo, fragmentos de código y muchos comentarios excelentes; Chris Kle

=== Agradecimientos a la Tercera Edición

_Por David A. Harding_

La introducción al protocolo de firma Schnorr no interactivo que
comienza describiendo primero el protocolo de identidad interactivo de Schnorr
en <<schnorr_signatures>> estuvo fuertemente influenciado por la introducción
el tema en "Borrommean Ring Signatures" (2015) de Gregory Maxwell y
Andrés Poelstra. Estoy profundamente en deuda con cada uno de ellos por todos sus
ha proporcionado asistencia gratuitamente durante el último decenio.

Se proporcionaron valiosas revisiones técnicas sobre los borradores de este manuscrito.
por Jorge Lesmes, Olaoluwa Osuntokun, René Pickhardt y Mark "Murch"
Erhardt. En particular, la increíblemente profunda y perspicaz interpretación de Murch
revisión y su voluntad de evaluar múltiples iteraciones de la misma
texto, han elevado la calidad de este libro más allá de mi nivel más alto.
Expectativas.

También tengo una deuda de gratitud con Jimmy Song por recomendarme para este
proyecto, a mi coautor Andreas por permitirme actualizar su
texto más vendido, a Angela Rufino por guiarme a través del libro O'Reilly
proceso de autoría y a todo el resto del personal de O'Reilly por hacer
La redacción de la tercera edición fue una experiencia placentera y productiva.

Finalmente, no sé cómo puedo agradecer a todos los contribuyentes de Bitcoin.
que me han ayudado en mi viaje, desde la creación del software que uso hasta
enseñarme cómo funciona, ayudarme a transmitir el poco conocimiento
He ganado. Hay demasiados de ustedes para enumerar sus nombres, pero creo
de ustedes a menudo y sé que mis contribuciones a este libro no habrían
sido posible sin todo lo que has hecho por mí.

[[github_contrib]]
=== Borrador de lanzamiento anticipado (contribuciones de GitHub)

Muchos contribuyentes ofrecieron comentarios, correcciones y adiciones al borrador de publicación anticipada en GitHub. Gracias a todos por sus contribuciones a este libro.

A continuación se muestra una lista de contribuyentes notables de GitHub, incluido su ID de GitHub entre paréntesis:

include::meta/github_contrib.adoc[]
