[prefacio]
== Prefacio

=== Escribiendo el Libro de Bitcoin

Yo (Andreas) me topé por primera vez con Bitcoin a mediados de 2011. Mi reacción inmediata fue más o menos "¡Pfft! ¡Dinero nerd!" y lo ignoré durante otros seis meses, sin comprender su importancia. Ésta es una reacción que he visto repetida entre muchas de las personas más inteligentes que conozco, lo que me da cierto consuelo. La segunda vez que me encontré con Bitcoin, en una discusión en una lista de correo, decidí leer el documento técnico escrito por Satoshi Nakamoto y ver de qué se trataba. Todavía recuerdo el momento en que terminé de leer esas nueve páginas, cuando me di cuenta de que Bitcoin no era simplemente una moneda digital, sino una red de confianza que también podía proporcionar la base para mucho más que solo monedas. Darme cuenta de que "esto no es dinero, es una red de confianza descentralizada" me inició en un viaje de cuatro meses para devorar cada fragmento de información sobre Bitcoin que pude encontrar. Me obsesioné y cautivé, pasando 12 horas o más cada día pegado a una pantalla, leyendo, escribiendo, codificando y aprendiendo todo lo que podía. Salí de este estado de fuga, con más de 20 libras menos por la falta de comidas consistentes, decidido a dedicarme a trabajar en Bitcoin.

Dos años más tarde, después de crear una serie de pequeñas empresas emergentes para explorar diversos servicios y productos relacionados con Bitcoin, decidí que era hora de escribir mi primer libro. Bitcoin fue el tema que me llevó a un frenesí de creatividad y consumió mis pensamientos; Era la tecnología más emocionante que había encontrado desde Internet. Había llegado el momento de compartir mi pasión por esta asombrosa tecnología con una audiencia más amplia.

=== Público Objetivo

Este libro está destinado principalmente a programadores. Si puede utilizar un lenguaje de programación, este libro le enseñará cómo funcionan las monedas criptográficas, cómo utilizarlas y cómo desarrollar software que funcione con ellas. Los primeros capítulos también son adecuados como una introducción en profundidad a Bitcoin para los no codificadores, aquellos que intentan comprender el funcionamiento interno de Bitcoin y las criptomonedas.

=== ¿Por Qué Hay Insectos en la Portada?

La hormiga cortadora de hojas es una especie que exhibe un comportamiento muy complejo en un superorganismo de colonia, pero cada hormiga individual opera según un conjunto de reglas simples impulsadas por la interacción social y el intercambio de olores químicos (feromonas). Según Wikipedia: "Junto a los humanos, las hormigas cortadoras de hojas forman las sociedades animales más grandes y complejas de la Tierra". Las hormigas cortadoras de hojas en realidad no comen hojas, sino que las usan para cultivar un hongo, que es la fuente central de alimento de la colonia. ¿Obtén éso? ¡Estas hormigas están cultivando!

Aunque las hormigas forman una sociedad basada en castas y tienen una reina para producir descendencia, no existe una autoridad central o un líder en una colonia de hormigas. El comportamiento altamente inteligente y sofisticado exhibido por una colonia multimillonaria es una propiedad emergente de la interacción de los individuos en una red social.

La naturaleza demuestra que los sistemas descentralizados pueden ser resilientes y producir una complejidad emergente y una sofisticación increíble sin la necesidad de una autoridad central, jerarquía o partes complejas.

Bitcoin es una red descentralizada altamente sofisticada que puede respaldar innumerables procesos financieros. Sin embargo, cada nodo de la red Bitcoin sigue unas cuantas reglas sencillas. La interacción entre muchos nodos es lo que conduce al surgimiento de un comportamiento sofisticado, no una complejidad inherente o confianza en un solo nodo. Como una colonia de hormigas, la red Bitcoin es una red resistente de nodos simples que siguen reglas simples y que juntos pueden hacer cosas asombrosas sin ninguna coordinación central.

=== Las Convenciones Usadas en Este Libro

En este libro se utilizan las siguientes convenciones tipográficas:

_Itálica_:: Indica nuevos términos, URL, direcciones de correo electrónico, nombres de archivos y extensiones de archivos.

+Ancho Constante+:: Se utiliza para listados de programas, así como dentro de párrafos para hacer referencia a elementos del programa, como nombres de funciones o variables, bases de datos, tipos de datos, variables de entorno, declaraciones y palabras clave.

**`Negrita de Ancho Constante`**:: Muestra comandos u otro texto que el usuario debe escribir literalmente.

_++Cursiva de Ancho Constante++_:: Muestra texto que debe reemplazarse con valores proporcionados por el usuario o por valores determinados por el contexto.


[TIP]
====
Este elemento significa un consejo o sugerencia.
====

[NOTE]
====
Este elemento significa una nota general.
====

[WARNING]
====
Este elemento indica una advertencia o precaución.
====

=== Ejemplos de Código

Todos los fragmentos de código se pueden replicar en la mayoría de los sistemas operativos con una instalación mínima de compiladores e intérpretes para los lenguajes correspondientes. Cuando sea necesario, proporcionamos instrucciones de instalación básicas y ejemplos paso a paso del resultado de esas instrucciones.

Some of the code snippets and code output have been reformatted for print. In all such cases, the lines have been split by a backslash (\) character, followed by a newline character. When transcribing the examples, remove those two characters and join the lines again and you should see identical results as shown in the example.

All the code snippets use real values and calculations where possible, so that you can build from example to example and see the same results in any code you write to calculate the same values.

=== Using Code Examples

This book is here to help you get your job done. In general, if example code is offered with this book, you may use it in your programs and documentation. You do not need to contact us for permission unless you’re reproducing a significant portion of the code. For example, writing a program that uses several chunks of code from this book does not require permission. Selling or distributing examples from O’Reilly books does require permission. Answering a question by citing this book and quoting example code does not require permission. Incorporating a significant amount of example code from this book into your product’s documentation does require permission.

We appreciate, but do not require, attribution. An attribution usually includes [.keep-together]#the title,# author, publisher, and ISBN. For example: “_Mastering Bitcoin_, 3rd ed., by [.keep-together]#Andreas M.# Antonopoulos and David A. Harding (O’Reilly). Copyright 2024 David Harding, ISBN 978-1-098-15009-9.”

Some editions of this book are offered under an open source license, such as https://oreil.ly/RzUHE[CC-BY-NC], in which case the terms of that license apply.

If you feel your use of code examples falls outside fair use or the permission given above, feel free to contact us at pass:[<a href="mailto:permissions@oreilly.com">permissions@oreilly.com</a>].

=== Changes Since the Previous Edition

include::meta/third_edition_changes.asciidoc[]

=== Bitcoin Addresses and Transactions in This Book

The Bitcoin addresses, transactions, keys, QR codes, and blockchain data used in this book are, for the most part, real. That means you can browse the blockchain, look at the transactions offered as examples, retrieve them with your own scripts or programs, etc.

However, note that the private keys used to construct addresses are either printed in this book or have been "burned." That means if you send money to any of these addresses, the money will either be lost forever, or in some cases everyone who can read the book can take it using the private keys printed in here.

[WARNING]
====
DO NOT SEND MONEY TO ANY OF THE ADDRESSES IN THIS BOOK. Your money will be taken by another reader or lost forever.
====

=== O'Reilly Online Learning
[role = "ormenabled"]
[NOTE]
====
For more than 40 years, pass:[<a href="https://oreilly.com" class="orm:hideurl"><em class="hyperlink">O’Reilly Media</em></a>] has provided technology and business training, knowledge, and insight to help companies succeed.
====

Our unique network of experts and innovators share their knowledge and expertise through books, articles, and our online learning platform. O’Reilly’s online learning platform gives you on-demand access to live training courses, in-depth learning paths, interactive coding environments, and a vast collection of text and video from O'Reilly and 200+ other publishers. For more information, visit pass:[<a href="https://oreilly.com" class="orm:hideurl"><em>https://oreilly.com</em></a>].

=== How to Contact Us

Please address comments and questions concerning this book to the publisher:

++++
<ul class="simplelist">
  <li>O’Reilly Media, Inc.</li>
  <li>1005 Gravenstein Highway North</li>
  <li>Sebastopol, CA 95472</li>
  <li>800-889-8969 (in the United States or Canada)</li>
  <li>707-829-7019 (international or local)</li>
  <li>707-829-0104 (fax)</li>
  <li><a class="email" href="mailto:support@oreilly.com"><em>support@oreilly.com</em></a></li>
  <li><a href="https://www.oreilly.com/about/contact.html"><em>https://www.oreilly.com/about/contact.html</em></a></li>
</ul>
++++

We have a web page for this book, where we list errata, examples, and any additional information. You can access this page at link:$$https://oreil.ly/MasteringBitcoin3e$$[].

++++
<!--Don't forget to update the link above.-->
++++

For news and information about our books and courses, visit link:$$https://oreilly.com$$[].

Find us on LinkedIn: link:$$https://linkedin.com/company/oreilly-media$$[].

Follow us on Twitter: link:$$https://twitter.com/oreillymedia$$[].

Watch us on YouTube: link:$$https://youtube.com/oreillymedia$$[].


=== Contacting the Authors

++++
<p class="left-align">
You can contact Andreas M. Antonopoulos on his personal site:
<span class="keep-together"><a href="https://antonopoulos.com"><em class="hyperlink">https://antonopoulos.com</em></a>.</span></p>
++++

Follow Andreas on Facebook:
link:$$https://facebook.com/AndreasMAntonopoulos$$[].

Follow Andreas on Twitter:
link:$$https://twitter.com/aantonop$$[].

Follow Andreas on LinkedIn:
link:$$https://linkedin.com/company/aantonop$$[].

Many thanks to all of Andreas's patrons who support his work through monthly donations. You can follow his Patreon page here:
link:$$https://patreon.com/aantonop$$[].

Information about _Mastering Bitcoin_, as well as Andreas's Open Edition and translations, is available on
link:$$https://bitcoinbook.info$$[].

You can contact David A. Harding on his personal site:
link:$$https://dtrt.org$$[].

=== Acknowledgments for the First and Second Editions

_By Andreas M. Antonopoulos_

This book represents the efforts and contributions of many people. I am grateful for all the help I received from friends, colleagues, and even complete strangers, who joined me in this effort to write the definitive technical book on cryptocurrencies and Bitcoin.

It is impossible to make a distinction between the Bitcoin technology and the Bitcoin community, and this book is as much a product of that community as it is a book on the technology. My work on this book was encouraged, cheered on, supported, and rewarded by the entire Bitcoin community from the very beginning until the very end. More than anything, this book has allowed me to be part of a wonderful community for two years and I can't thank you enough for accepting me into this community. There are far too many people to mention by name—people I've met at conferences, events, seminars, meetups, pizza gatherings, and small private gatherings, as well as many who communicated with me by Twitter, on reddit, on bitcointalk.org, and on GitHub who have had an impact on this book. Every idea, analogy, question, answer, and explanation you find in this book was at some point inspired, tested, or improved through my interactions with the community. Thank you all for your support; without you this book would not have happened. I am forever grateful.

The journey to becoming an author starts long before the first book, of course. My first language (and schooling) was Greek, so I had to take a remedial English writing course in my first year of university. I owe thanks to Diana Kordas, my English writing teacher, who helped me build confidence and skills that year. Later, as a professional, I developed my technical writing skills on the topic of data centers, writing for _Network World_ magazine. I owe thanks to John Dix and John Gallant, who gave me my first writing job as a columnist at _Network World_ and to my editor Michael Cooney and my colleague Johna Till Johnson who edited my columns and made them fit for publication. Writing 500 words a week for four years gave me enough experience to eventually consider becoming an author.

Thanks also to those who supported me when I submitted my book proposal to O'Reilly by providing references and reviewing the proposal. Specifically, thanks to John Gallant, Gregory Ness, Richard Stiennon, Joel Snyder, Adam B. Levine, Sandra Gittlen, John Dix, Johna Till Johnson, Roger Ver, and Jon Matonis. Special thanks to Richard Kagan and Tymon Mattoszko, who reviewed early versions of the proposal and Matthew Taylor, who copyedited the proposal.

Thanks to Cricket Liu, author of the O'Reilly title _DNS and BIND_, who introduced me to O'Reilly. Thanks also to Michael Loukides and Allyson MacDonald at O'Reilly, who worked for months to help make this book happen. Allyson was especially patient when deadlines were missed and deliverables delayed as life intervened in our planned schedule. For the second edition, I thank Timothy McGovern for guiding the process, Kim Cofer for patiently editing, and Rebecca Panzer for illustrating many new diagrams.

The first few drafts of the first few chapters were the hardest, because Bitcoin is a difficult subject to unravel. Every time I pulled on one thread of the Bitcoin technology, I had to pull on the whole thing. I repeatedly got stuck and a bit despondent as I struggled to make the topic easy to understand and create a narrative around such a dense technical subject. Eventually, I decided to tell the story of Bitcoin through the stories of the people using Bitcoin and the whole book became a lot easier to write. I owe thanks to my friend and mentor, Richard Kagan, who helped me unravel the story and get past the moments of writer's block. I thank Pamela Morgan, who reviewed early drafts of each chapter in the first and second edition of the book and asked the hard questions to make them better. Also, thanks to the developers of the San Francisco Bitcoin Developers Meetup group as well as Taariq Lewis and Denise Terry for helping test the early material. Thanks also to Andrew Naugler for infographic design.

During the development of the book, I made early drafts available on GitHub and invited public comments. More than a hundred comments, suggestions, corrections, and contributions were submitted in response. Those contributions are explicitly acknowledged, with my thanks, in <<github_contrib>>. Most of all, my sincere thanks to my volunteer GitHub editors Ming T. Nguyen (1st edition) and Will Binns (2nd edition), who worked tirelessly to curate, manage, and resolve pull requests, issue reports, and perform bug fixes on GitHub.

Once the book was drafted, it went through several rounds of technical review. Thanks to Cricket Liu and Lorne Lantz for their thorough review, comments, and support.

Several Bitcoin developers contributed code samples, reviews, comments, and encouragement. Thanks to Amir Taaki and Eric Voskuil for example code snippets and many great comments; Chris Kleeschulte for contributing information about Bitcore; Vitalik Buterin and Richard Kiss for help with elliptic curve math and code contributions; Gavin Andresen for corrections, comments, and encouragement; Michalis Kargakis for comments, contributions, and btcd writeup; and Robin Inge for errata submissions improving the second print. In the second edition, I again received a lot of help from many Bitcoin Core developers, including Eric Lombrozo who demystified segregated witness, Luke Dashjr who helped improve the chapter on transactions, Johnson Lau who reviewed segregated witness and other chapters, and many others. I owe thanks to Joseph Poon, Tadge Dryja, and Olaoluwa Osuntokun who explained Lightning Network, reviewed my writing, and answered questions when I got stuck.

I owe my love of words and books to my mother, Theresa, who raised me in a house with books lining every wall. My mother also bought me my first computer in 1982, despite being a self-described technophobe. My father, Menelaos, a civil engineer who just published his first book at 80 years old, was the one who taught me logical and analytical thinking and a love of science and engineering.

Thank you all for supporting me throughout this journey.

=== Acknowledgments for the Third Edition

_By David A. Harding_

The introduction to the noninteractive schnorr signature protocol that
starts with first describing the interactive schnorr identity protocol
in <<schnorr_signatures>> was heavily influenced by the introduction to
the subject in "Borrommean Ring Signatures" (2015) by Gregory Maxwell and
Andrew Poelstra.  I am deeply indebted to each of them for all of their
freely provided assistance over the past decade.

Invaluable technical reviews on drafts of this manuscript were provided
by Jorge Lesmes, Olaoluwa Osuntokun, René Pickhardt, and Mark "Murch"
Erhardt.  In particular, Murch's incredibly in-depth and insightful
review, and his willingness to evaluate multiple iterations of the same
text, have elevated the quality of this book beyond my highest
expectations.

I also owe a debt of gratitude to Jimmy Song for suggesting me for this
project, to my coauthor Andreas for allowing me to update his
bestselling text, to Angela Rufino for guiding me through the O'Reilly
authorship process, and to all of the other staff at O'Reilly for making
the writing of the third edition a pleasant and productive experience.

Finally, I don't know how I can thank all of the Bitcoin contributors
who have helped me on my journey--from creating the software I use, to
teaching me how it works, to helping me pass on what little knowledge
I've gained.  There are too many of you to list your names, but I think
of you often and know that my contributions to this book would not have
been possible without all that you've done for me.

[[github_contrib]]
=== Early Release Draft (GitHub Contributions)

Many contributors offered comments, corrections, and additions to the early-release draft on GitHub. Thank you all for your contributions to this book.

Following is a list of notable GitHub contributors, including their GitHub ID in parentheses:

include::meta/github_contrib.adoc[]
